name: dart_server_app
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_hotreload: ^1.5.0
  shelf_multipart: ^2.0.0
  intl: ^0.20.1
  path: ^1.9.1
  mime: ^1.0.6

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
